name: push_blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v3
      # - name: creates output
      #   run:  sh ./build.sh # some command from your repository that creates
                            # output to "source-directory" ("output" in the example)
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # API_TOKEN_GITHUB: ${{ secrets.TOKEN }}

          SSH_DEPLOY_KEY: ${{ secrets.PRIVERT_KEY }}
        with:
          source-directory: './blog'
          destination-github-username: 'Ruixi-rebirth'
          destination-repository-name: 'Ruixi-rebirth.github.io'
          user-email: ruixirebirth@gmail.com
          target-branch: source
